add rawtext syntax for lovelace and custom body-inset
andreasKroepelin/lovelace pull request #3
Opened 2023-11-04 11:06 UTC by OrangeX4

https://github.com/andreasKroepelin/lovelace/issues/2

2024-01-04 06:37 UTC, OrangeX4 commented
@andreasKroepelin Any progress here?

2024-01-08 22:07 UTC, andreasKroepelin requested changes
Thanks for the PR, I made some suggestions regarding code style. Looks good otherwise!

2024-01-08 22:07 UTC, andreasKroepelin commented on lib.typ
> +    let current-indent = if (whitespaces != none) { whitespaces.len() } else { 0 }
```suggestion
    let current-indent = if whitespaces != none { whitespaces.len() } else { 0 }
```

2024-01-08 22:07 UTC, andreasKroepelin commented on lib.typ
> +    if (indent == 0 and current-indent != 0) {
```suggestion
    if indent == 0 and current-indent != 0 {
```

2024-01-08 22:07 UTC, andreasKroepelin commented on lib.typ
> +    if (current-indent > last-indent) {
```suggestion
    if current-indent > last-indent {
```

2024-01-08 22:07 UTC, andreasKroepelin commented on lib.typ
> +    } else if (current-indent < last-indent) {
```suggestion
    } else if current-indent < last-indent {
```

2024-01-08 22:07 UTC, andreasKroepelin commented on lib.typ
> +    if type(child) == "content" and child.func() == raw {
```suggestion
    if type(child) == content and child.func() == raw {
```

2024-01-08 22:07 UTC, andreasKroepelin commented on lib.typ
> +      children = children + _typst2lovelace(child, scope: scope)
```suggestion
      children.push(_typst2lovelace(child, scope: scope))
```
for consistency with the other branch

2024-01-08 22:16 UTC, andreasKroepelin requested changes
Just some more things that came up.
- [ ] Also, please add an explanation for the `scope` keyword argument to the readme

2024-01-08 22:16 UTC, andreasKroepelin commented on README.md
> +- `body-inset`: the inset of body, default to be `(bottom: 5pt)`
```suggestion
- `body-inset`: the inset of body, default `(bottom: 5pt)`
```

for consistency with the other bullet points

2024-01-08 22:16 UTC, andreasKroepelin commented on README.md
> +#algorithm(
Maybe actually don't use `#algorithm` here, it is not necessary for a minimal example.

2024-01-09 02:23 UTC, andreasKroepelin commented
Alright, I resolved some code style issues and adopted a new API. Thanks again for your contribution!

2024-01-09 02:23 UTC, merged

2024-01-09 02:48 UTC, OrangeX4 commented
Thanks for review!